Repository vshn/appcat, pull requests merged in 2023-07, with the labels that each got.

#32 Update postres backup table
  apis/appcat/v1/vshn_postgres_backup_types.go
  pkg/apiserver/vshn/postgres/table.go
Labels: documentation, enhancement

#34 Update target SLA in SLA Reporter
  cmd/slareport.go
  pkg/slareport/prom.go
  pkg/slareport/prom_test.go
Labels: enhancement

#36 Add some dev-notes about comp functions
  docs/antora-preview.mk
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/dev-notes.adoc
Labels: documentation

#38 Add vshn postgres repack to maintenance
  apis/stackgres/v1/sgdbops.go
  cmd/maintenance.go
  docs/modules/ROOT/pages/explanations/comp-functions/vshn-postgres.adoc
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
Labels: enhancement

#39 Fix maintenance secret reference in pg
  pkg/comp-functions/functions/vshn-postgres-func/maintenance.go
Labels: bug

#37 Add user configurable extensions
  Makefile
  apis/stackgres/v1/groupversion_info.go
  apis/stackgres/v1/sgpostresconfig.go
  apis/stackgres/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/stackgres.io_sgpostgresconfigs.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  pkg/comp-functions/functions/vshn-postgres-func/extensions.go
  pkg/comp-functions/functions/vshn-postgres-func/extensions_test.go
  pkg/comp-functions/runtime/desired.go
  test/transforms/vshn-postgres/extensions/01-GivenAlreadyEnabled.yaml
  test/transforms/vshn-postgres/extensions/01-GivenFreshConfig.yaml
Labels: enhancement

#41 Improve logging
  cmd/grpc.go
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/comp-functions/debug.adoc
  go.sum
  pkg/comp-functions/functions/helper/funcio.go
  pkg/comp-functions/functions/vshn-postgres-func/encrypted_pvc.go
  pkg/comp-functions/runtime/desired.go
  pkg/comp-functions/runtime/logger.go
  pkg/comp-functions/runtime/observed.go
  pkg/comp-functions/runtime/run.go
  pkg/comp-functions/runtime/runtime.go
Labels: enhancement

#43 Fix edge cases in PostgreSQL maintenance
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
Labels: bug

#44 Add option to configure multiple PostgreSQL instances
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  pkg/comp-functions/functions/vshn-postgres-func/replication.go
  pkg/comp-functions/functions/vshn-postgres-func/replication_test.go
  test/transforms/vshn-postgres/replication/01-GivenMulitInstance.yaml
Labels: enhancement

#33 Add support for restoring redis backups
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  pkg/comp-functions/functions/vshnredis/restore.go
  pkg/comp-functions/functions/vshnredis/restore_test.go
  pkg/comp-functions/functions/vshnredis/script/cleanupRestore.sh
  pkg/comp-functions/functions/vshnredis/script/prepRestore.sh
  pkg/comp-functions/functions/vshnredis/script/restore.sh
  test/transforms/vshnredis/restore/01-GivenNoRestoreConfig.yaml
  test/transforms/vshnredis/restore/01-GivenRestoreConfig.yaml
  test/transforms/vshnredis/restore/01-GivenRestoreConfigNoBN.yaml
  test/transforms/vshnredis/restore/01-GivenRestoreConfigNoCN.yaml
Labels: enhancement, go

#48 Use unique key to keep track of probers instead of the whole ProberInfo
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/manager_test.go
Labels: bug

#50 Fix display issue for Redis Backups
  pkg/apiserver/vshn/redis/table.go
  pkg/apiserver/vshn/redis/table_test.go
Labels: bug
