Repository vshn/appcat, pull requests merged in 2023-08, with the labels that each got.

#49 Allow upgrading redis to newer versions
  pkg/comp-functions/functions/vshnredis/release.go
  pkg/comp-functions/functions/vshnredis/release_test.go
  test/transforms/vshnredis/release/03_version_update.yaml.tmpl
Labels: enhancement

#46 Add external connection IPs to connection secret if service type is set to LoadBalancer for PostgreSQL Managed by VSHN
  README.md
  apis/vshn/v1/dbaas_vshn_postgresql.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  docs/antora-build.mk
  docs/modules/ROOT/nav.adoc
  go.mod
  go.sum
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer_test.go
  pkg/comp-functions/runtime/desired.go
  pkg/comp-functions/runtime/runtime.go
  test/transforms/vshn-postgres/loadbalancer/01-LoadBalancerSet.yaml
  test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
Labels: enhancement

#45 Add redis maintenance docs
  docs/modules/ROOT/pages/explanations/comp-functions/vshn-redis.adoc
Labels: documentation

#52 Fix an issue with statefulsets stuck in deletion
  pkg/comp-functions/functions/vshnredis/script/recreate.sh
Labels: bug

#55 Add some vscode samples
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/examples/vscode.adoc
Labels: documentation

#54 Adjusting code to cooperate with Cilium
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer_test.go
  test/transforms/vshn-postgres/loadbalancer/01-LoadBalancerSet.yaml
  test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
Labels: bug, enhancement, go

#57 fixing url.go function
  pkg/comp-functions/functions/vshn-postgres-func/url.go
Labels: bug

#58 fixing objectname to avoid name collisions
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
  test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
Labels: bug

#60 renaming object, so it has more meaningful name and it's easier to debug
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
  test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
Labels: enhancement

#53 Add service level guaranteed availability
  README.md
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/postgresql.go
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller_test.go
Labels: enhancement

#62 Adjust maintenance procedure for stackgres upgrades
  pkg/maintenance/postgresql.go
Labels: enhancement

#63 Redis prober
  Makefile
  cmd/sliexporter.go
  config/sliexporter/rbac/role.yaml
  go.mod
  go.sum
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/redis.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: enhancement

#61 Add webhook support for quota checking
  Makefile
  README.md
  cmd/controller.go
  cmd/grpc.go
  config/controller/cluster-role-binding.yaml
  config/controller/cluster-role.yaml
  config/controller/deployment.yaml
  config/controller/pg-webhook.yaml
  config/controller/redis-webhook.yaml
  config/controller/role-binding-leader-election.yaml
  config/controller/role-leader-election.yaml
  config/controller/service-account.yaml
  config/controller/webhook-service.yaml
  docs/modules/ROOT/assets/images/quotas.excalidraw.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/webhooks.adoc
  pkg/common/quotas/plans.go
  pkg/common/quotas/plans_test.go
  pkg/common/quotas/quotas.go
  pkg/common/quotas/quotas_test.go
  pkg/common/quotas/resources.go
  pkg/common/quotas/resources_test.go
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/comp-functions/functions/common/namespace-quotas_test.go
  pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
  pkg/comp-functions/runtime/runtime.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
  test/transforms/common/quotas/01_default.yaml
Labels: enhancement

#64 Fix appcat documentation
  README.md
  docs/antora-playbook.yml
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
  go.sum
Labels: documentation

#66 Fix docs workflow
  .github/workflows/docs.yml
  docs/modules/ROOT/nav.adoc
  docs/package.json
Labels: bug
