Repository vshn/appcat, pull requests merged in 2023-06, with the labels that each got.

#20 Add SLA report template
  pkg/reporting/render.go
  pkg/reporting/render_test.go
  pkg/reporting/template/sla-report.txt
Labels: enhancement

#22 Extend maintenance to support minor updates
  Makefile
  apis/appcat/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  cmd/grpc.go
  cmd/maintenance.go
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/comp-functions/vshn-postgres.adoc
  go.mod
  go.sum
  login.json
  main.go
  pkg/comp-functions/functions/vshn-postgres-func/maintenance.go
  pkg/comp-functions/functions/vshn-postgres-func/maintenance_test.go
  pkg/comp-functions/runtime/observed.go
  pkg/comp-functions/runtime/runtime.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
  pkg/scheme.go
  test/transforms/vshn-postgres/maintenance/01-GivenSchedule.yaml
  test/transforms/vshn-postgres/maintenance/02-GivenNoSchedule.yaml
Labels: enhancement

#23 Add support for multiple buckets in the miniodev environment
  apis/v1/groupversion_info.go
  cmd/grpc.go
  go.mod
  go.sum
  pkg/comp-functions/functions/miniodev/objectbucket.go
  pkg/scheme.go
Labels: enhancement

#21 Adding mailgun alerting if customer specify email address in claim
  apis/vshn/v1/dbaas_vshn_postgresql.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting.go
  pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting_test.go
  test/transforms/vshn-postgres/alerting/06-GivenNoEmail.yaml
  test/transforms/vshn-postgres/alerting/07-GivenEmail.yaml
  test/transforms/vshn-postgres/alerting/08-GivenEmptyEmail.yaml
Labels: enhancement, go

#24 Add SLA reporting tool
  Makefile
  cmd/slareport.go
  config/sliexporter/rbac/role.yaml
  config/sliexporter/rbac/role_binding.yaml
  config/sliexporter/rbac/service_account.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/slareports.adoc
  go.mod
  go.sum
  main.go
  pkg/slareport/prom.go
  pkg/slareport/prom_test.go
  pkg/slareport/render.go
  pkg/slareport/render_test.go
  pkg/slareport/s3.go
  pkg/slareport/template/sla-report.txt
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/postgresql.go
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller_test.go
Labels: enhancement

#28 Fix composite label name
  pkg/apiserver/vshn/postgres/vshnpostgresql.go
Labels: bug

#26 Add Redis Backup Listing
  .gitignore
  apis/appcat/v1/generated.pb.go
  apis/appcat/v1/register.go
  apis/appcat/v1/vshn_redis_backup_types.go
  apis/appcat/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/apiserver.go
  config/apiserver/role.yaml
  go.mod
  go.sum
  pkg/apiserver/common.go
  pkg/apiserver/vshn/k8up/k8up.go
  pkg/apiserver/vshn/postgres/list.go
  pkg/apiserver/vshn/postgres/multiwatch.go
  pkg/apiserver/vshn/redis/backup.go
  pkg/apiserver/vshn/redis/common_test.go
  pkg/apiserver/vshn/redis/create.go
  pkg/apiserver/vshn/redis/delete.go
  pkg/apiserver/vshn/redis/get.go
  pkg/apiserver/vshn/redis/get_test.go
  pkg/apiserver/vshn/redis/list.go
  pkg/apiserver/vshn/redis/list_test.go
  pkg/apiserver/vshn/redis/table.go
  pkg/apiserver/vshn/redis/table_test.go
  pkg/apiserver/vshn/redis/update.go
  pkg/apiserver/vshn/redis/vshnredis.go
  pkg/apiserver/vshn/redis/watch.go
  pkg/scheme.go
Labels: enhancement

#29 Add redis maintenance comp function
  cmd/grpc.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/commontest/commontest.go
  pkg/comp-functions/functions/vshn-postgres-func/alerting_test.go
  pkg/comp-functions/functions/vshn-postgres-func/encrypted_pvc_test.go
  pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting_test.go
  pkg/comp-functions/functions/vshn-postgres-func/maintenance.go
  pkg/comp-functions/functions/vshn-postgres-func/restart_test.go
  pkg/comp-functions/functions/vshn-postgres-func/schedule_test.go
  pkg/comp-functions/functions/vshn-postgres-func/url_test.go
  pkg/comp-functions/functions/vshnredis/backup_test.go
  pkg/comp-functions/functions/vshnredis/common_test.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/comp-functions/functions/vshnredis/utils.go
Labels: enhancement

#31 Actually disable the AOF rewrite before backup
  pkg/comp-functions/functions/vshnredis/script/backup.sh
Labels: bug

#30 Add Redis maintenace job
  cmd/apiserver.go
  cmd/grpc.go
  cmd/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/vshn-postgres-func/maintenance.go
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/functions/vshnredis/backup_test.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/comp-functions/functions/vshnredis/release.go
  pkg/comp-functions/functions/vshnredis/release_test.go
  pkg/controller/postgres/deletion_protection.go
  pkg/controller/postgres/deletion_protection_test.go
  pkg/maintenance/redis.go
  pkg/maintenance/redis_test.go
  test/transforms/vshnredis/release/01_default.yaml
Labels: enhancement
