Repository vshn/appcat, pull requests merged in 2023-11, with the labels that each got.

#97 Fix prober when namespace claim is deleted
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: bug

#95 Add Sli prober for VSHNMinio
  apis/v1/objectstorage_types.go
  apis/v1/zz_generated.deepcopy.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/sliexporter.go
  config/sliexporter/rbac/role.yaml
  crds/appcat.vshn.io_objectbuckets.yaml
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
  pkg/sliexporter/probes/minio.go
  pkg/sliexporter/probes/minio_test.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller_test.go
Labels: enhancement

#100 Adjust wording for HA check
  pkg/controller/webhooks/postgresql.go
Labels: enhancement

#102 Wrap sli bucket into object
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
Labels: bug

#98 Add Mailgun and custom Alertmanagerconfig to Redis
  Makefile
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  pkg/comp-functions/functions/common/alerting.go
  pkg/comp-functions/functions/common/alerting_test.go
  pkg/comp-functions/functions/common/mailgun_alerting.go
  pkg/comp-functions/functions/common/mailgun_alerting_test.go
  pkg/comp-functions/functions/vshn-postgres-func/alerting.go
  pkg/scheme.go
  test/transforms/vshn-postgres/alerting/03-GivenConfigRefAndSecret.yaml
  test/transforms/vshn-postgres/alerting/04-GivenConfigTemplateAndSecret.yaml
Labels: enhancement

#104 Crossplane 1.14 docs
  README.md
  docs/modules/ROOT/pages/explanations/comp-functions/debug.adoc
  docs/modules/ROOT/pages/explanations/comp-functions/runtime.adoc
  docs/modules/ROOT/pages/explanations/connectiondetails.adoc
  docs/modules/ROOT/pages/explanations/dev-notes.adoc
Labels: documentation

#107 Adjust docs for crossplane 1.14
  README.md
  docs/modules/ROOT/pages/explanations/comp-functions/debug.adoc
  docs/modules/ROOT/pages/explanations/comp-functions/runtime.adoc
  docs/modules/ROOT/pages/explanations/connectiondetails.adoc
  docs/modules/ROOT/pages/explanations/dev-notes.adoc
Labels: documentation

#109 Fix quota namespace not found
  package/package.mk
  pkg/comp-functions/functions/common/namespace-quotas.go
Labels: bug

#105 Add MariaDB service
  Makefile
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/zz_generated.deepcopy.go
  apis/vshn/v1/zz_generated.managed.go
  apis/vshn/v1/zz_generated.managedlist.go
  cmd/functions.go
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnminios.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/bootstrap_api.adoc
  go.mod
  go.sum
  hack/bootstrap/template.go
  hack/bootstrap/template/api.txt
  package/crossplane.yaml
  pkg/comp-functions/functions/common/netpol.go
  pkg/comp-functions/functions/common/resources.go
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy_test.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/scheme.go
  test/functions/vshnmariadb/deploy/01_default.yaml
Labels: enhancement
