Repository vshn/appcat, pull requests merged in 2023-09, with the labels that each got.

#67 Add webhook to validate serviceLevel
  Makefile
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
Labels: enhancement

#68 Add service constraints to SLA reporter
  pkg/slareport/prom.go
  pkg/slareport/prom_test.go
Labels: bug

#70 Add Miniobucket composition function
  cmd/grpc.go
  config/apiserver/role.yaml
  config/sliexporter/rbac/role.yaml
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
  crds/stackgres.io_sgclusters.yaml
  crds/stackgres.io_sgdbops.yaml
  crds/stackgres.io_sgpostgresconfigs.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  go.mod
  go.sum
  pkg/comp-functions/functions/miniobucket/miniobucket.go
  pkg/comp-functions/functions/miniobucket/miniobucket_test.go
  pkg/comp-functions/functions/miniodev/objectbucket.go
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/runtime/desired.go
  pkg/controller/postgres/reconciler_test.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
  pkg/scheme.go
  test/empty.yaml
  test/mocks/mock_client.go
  test/transforms/miniobucket/bucket.yaml
Labels: enhancement

#72 Revert "Merge pull request #70 from vshn/add/miniobucket"
  cmd/grpc.go
  config/apiserver/role.yaml
  config/sliexporter/rbac/role.yaml
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
  crds/stackgres.io_sgclusters.yaml
  crds/stackgres.io_sgdbops.yaml
  crds/stackgres.io_sgpostgresconfigs.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  go.mod
  go.sum
  pkg/comp-functions/functions/miniobucket/miniobucket.go
  pkg/comp-functions/functions/miniobucket/miniobucket_test.go
  pkg/comp-functions/functions/miniodev/objectbucket.go
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/runtime/desired.go
  pkg/controller/postgres/reconciler_test.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
  pkg/scheme.go
  test/empty.yaml
  test/mocks/mock_client.go
  test/transforms/miniobucket/bucket.yaml
Labels: bug

#74 Avoid dropping the Organization label
  go.mod
  go.sum
  pkg/common/quotas/quotas.go
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/comp-functions/functions/common/namespace-quotas_test.go
Labels: bug

#69 Add API, CRD and composition function for minio
  .gitignore
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnminios.yaml
  pkg/common/quotas/quotas.go
  pkg/common/quotas/quotas_test.go
  pkg/common/utils/plans.go
  pkg/common/utils/plans_test.go
  pkg/common/utils/resources.go
  pkg/common/utils/resources_test.go
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/runtime/desired.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
  test/transforms/vshnminio/deploy/01_default.yaml
Labels: enhancement

#71 Add docs about connection details
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/connectiondetails.adoc
Labels: documentation

#75 Re-Add Minio Bucket Support
  cmd/grpc.go
  config/apiserver/aggregated-apiserver.yaml
  config/apiserver/apiserver-cert.yaml
  config/apiserver/apiserver-envs.yaml
  config/apiserver/apiservice.yaml
  config/apiserver/cluster-role-binding.yaml
  config/apiserver/namespace.yaml
  config/apiserver/role.yaml
  config/apiserver/service-account.yaml
  config/apiserver/service.yaml
  config/sliexporter/rbac/role.yaml
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
  crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
  crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
  crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
  crds/stackgres.io_sgclusters.yaml
  crds/stackgres.io_sgdbops.yaml
  crds/stackgres.io_sgpostgresconfigs.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  go.mod
  go.sum
  pkg/comp-functions/functions/miniobucket/miniobucket.go
  pkg/comp-functions/functions/miniobucket/miniobucket_test.go
  pkg/comp-functions/functions/miniodev/objectbucket.go
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/runtime/desired.go
  pkg/controller/postgres/reconciler_test.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
  pkg/scheme.go
  test/empty.yaml
  test/transforms/miniobucket/bucket.yaml
Labels: enhancement

#77 Minor changes to integrate with provider
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  crds/vshn.appcat.vshn.io_vshnminios.yaml
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnminio/providerconfig.go
  pkg/comp-functions/functions/vshnminio/providerconfig_test.go
  pkg/comp-functions/runtime/result.go
  pkg/scheme.go
  test/transforms/vshnminio/deploy/01_default.yaml
Labels: enhancement

#80 Use Bitnami Redis image to check for newer tags
  pkg/maintenance/redis.go
Labels: bug

#82 Add Minio Maintenance
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/grpc.go
  cmd/maintenance.go
  crds/vshn.appcat.vshn.io_vshnminios.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/helm-maintenance.adoc
  pkg/common/jsonpatch/jsonpatch.go
  pkg/comp-functions/functions/vshnminio/maintenance.go
  pkg/comp-functions/functions/vshnminio/utils.go
  pkg/controller/postgres/deletion_protection.go
  pkg/controller/postgres/deletion_protection_test.go
  pkg/maintenance/helm/helmpatcher.go
  pkg/maintenance/helm/helmpatcher_test.go
  pkg/maintenance/minio.go
  pkg/maintenance/minio_test.go
  pkg/maintenance/redis.go
  pkg/maintenance/redis_test.go
Labels: enhancement

#79 Switching Reconciliation in SLI Prober from claim to composite resource
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/zz_generated.deepcopy.go
  config/sliexporter/rbac/role.yaml
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: enhancement

#83 adding Redis URL
  cmd/grpc.go
  pkg/comp-functions/functions/vshnredis/redis_url.go
  pkg/comp-functions/functions/vshnredis/redis_url_test.go
Labels: enhancement

#81 Add instances label to prober metrics
  README.md
  apis/metadata/metadata_types.go
  apis/metadata/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/comp-functions/functions/common/namespace-quotas_test.go
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/postgresql.go
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/probes/redis.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: enhancement

#84 Override the Minio fullname
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
Labels: bug

#85 Add bucket deletion policy for Minio
  apis/v1/objectstorage_types.go
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  pkg/comp-functions/functions/miniobucket/miniobucket.go
Labels: enhancement

#78 Fix resource calculation by taking sidecars into account
  docs/modules/ROOT/pages/explanations/webhooks.adoc
  pkg/common/quotas/quotas.go
  pkg/common/quotas/quotas_test.go
  pkg/common/utils/resources.go
  pkg/common/utils/sidecars.go
  pkg/common/utils/sidecars_test.go
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  test/transforms/common/quotas/01_default.yaml
Labels: bug
