Repository vshn/appcat, pull requests merged in 2024-12, with the labels that each got.

#278 add TLS fix
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
Labels: bug, minor

#270 Enable nextcloud office billing
  apis/vshn/v1/vshn_nextcloud.go
  pkg/comp-functions/functions/common/billing.go
  pkg/comp-functions/functions/common/billing_test.go
  pkg/comp-functions/functions/vshnnextcloud/billing.go
  test/functions/common/billing.yaml
Labels: enhancement, minor

#274 Set the correct version for the SGCluster
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
  test/functions/vshn-postgres/deploy/01_default.yaml
Labels: bug, patch

#279 ensure correct TLS settings for nested VSHNPostgreSQLs
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/vshn_nextcloud.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
Labels: bug, minor

#281 Add add-on billing label
  pkg/comp-functions/functions/common/billing.go
  pkg/comp-functions/functions/common/billing_test.go
Labels: bug, patch

#273 Add support for remote control plane to SLI exporter
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  cmd/sliexporter.go
  pkg/apiserver/appcat/appcat.go
  pkg/apiserver/common.go
  pkg/apiserver/vshn/mariadb/backup.go
  pkg/apiserver/vshn/nextcloud/backup.go
  pkg/apiserver/vshn/postgres/backup.go
  pkg/apiserver/vshn/redis/backup.go
  pkg/common/utils/kinds.go
  pkg/comp-functions/functions/common/interfaces.go
  pkg/sliexporter/maintenance_controller/controller.go
  pkg/sliexporter/sli_reconciler/reconciler.go
  pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
  pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller_test.go
  pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go
  pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller_test.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller_test.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: minor

#285 fixing name for nextcloud deployment in collabora install script
  apis/vshn/v1/vshn_nextcloud.go
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
Labels: bug, minor

#286 correct default in postgresql crds
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
Labels: bug, patch

#284 Make sure backup retention is properly defaulted
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_nextcloud.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
Labels: patch
