Repository vshn/appcat, pull requests merged in 2024-01, with the labels that each got.

#120 Improve maintenance detection
  .gitignore
  cmd/sliexporter.go
  config/sliexporter/rbac/role.yaml
  go.mod
  go.sum
  pkg/scheme.go
  pkg/sliexporter/maintenance_controller/controller.go
  pkg/sliexporter/maintenance_controller/controller_test.go
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/manager_test.go
Labels: enhancement

#121 Add support nodeSelector for MariaDB offering
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  pkg/common/utils/plans.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
Labels: enhancement

#122 Add MariaDB Backups
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_redis.go
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/common/backup/backup_test.go
  pkg/comp-functions/functions/common/interfaces.go
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/common/release.go
  pkg/comp-functions/functions/vshnmariadb/backup.go
  pkg/comp-functions/functions/vshnmariadb/backup_test.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/comp-functions/functions/vshnmariadb/script/backup.sh
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/functions/vshnredis/backup_test.go
  pkg/comp-functions/functions/vshnredis/pvcresize.go
  pkg/comp-functions/functions/vshnredis/release.go
  test/functions/vshnmariadb/deploy/01_default.yaml
Labels: enhancement

#123 Fix bootstrap API docs
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/how-tos/bootstrap_api.adoc
Labels: documentation

#125 Move PostgreSQL connection details to cluster
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  pkg/comp-functions/functions/vshnpostgres/connection_details_test.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnpostgres/url.go
  pkg/comp-functions/functions/vshnpostgres/url_test.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/vshn-postgres/secrets/01_expected_no-instance-namespace.yaml
  test/functions/vshn-postgres/secrets/01_input_no-instance-namespace.yaml
  test/functions/vshn-postgres/secrets/02_input_function-io.yaml
Labels: bug

#127 Don't handle the organization label in quotas
  pkg/comp-functions/functions/common/instance_namespace.go
  pkg/comp-functions/functions/common/namespace-quotas.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: bug

#119 Adjust stackgres rest-api secret name for stackgres 1.7 upgrade
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  test/functions/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
Labels: enhancement
