Repository vshn/appcat, pull requests merged in 2024-07, with the labels that each got.

#184 Refactor and fix Resource calculations
  pkg/comp-functions/functions/common/resources.go
  pkg/comp-functions/functions/common/resources_test.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  test/functions/plans.yaml
Labels: bug

#187 Update dependencies
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  go.mod
  go.sum
  pkg/comp-functions/functions/common/alerting.go
  pkg/comp-functions/functions/common/mailgun_alerting.go
  pkg/comp-functions/functions/common/mailgun_alerting_test.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/common/password_test.go
  pkg/comp-functions/functions/common/rbac.go
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  pkg/comp-functions/functions/vshnpostgres/delay_cluster.go
  pkg/comp-functions/functions/vshnpostgres/encrypted_pvc_test.go
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnredis/pvcresize.go
  pkg/comp-functions/functions/vshnredis/pvcresize_test.go
  pkg/comp-functions/functions/vshnredis/restore_test.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/postgres/deletion_protection_test.go
  pkg/controller/postgres/reconciler.go
  pkg/controller/postgres/reconciler_test.go
  pkg/scheme.go
Labels: dependencies

#189 Fix wrong usage of `useExternalPostgreSQL` parameter and add better tests
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
  test/functions/vshnnextcloud/01_default.yaml
  test/functions/vshnnextcloud/02_no_pg.yaml
Labels: bug

#188 Refactor Minio to use generic service and generic ns bootstrap function
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
  pkg/comp-functions/functions/vshnminio/providerconfig.go
  test/functions/vshnminio/deploy/01_default.yaml
Labels: enhancement

#193 Set the FQDN for nextcloud as a required field
  apis/vshn/v1/common_types.go
  apis/vshn/v1/vshn_nextcloud.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
Labels: bug

#192 Add Nextcloud maintenance
  apis/vshn/v1/vshn_nextcloud.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
  pkg/comp-functions/functions/vshnnextcloud/files/nextcloud-post-upgrade.sh
  pkg/comp-functions/functions/vshnnextcloud/files/vshn-nextcloud.config.php
  pkg/comp-functions/functions/vshnnextcloud/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/register.go
  pkg/maintenance/keycloak.go
  pkg/maintenance/mariadb.go
  pkg/maintenance/minio.go
  pkg/maintenance/nextcloud.go
  pkg/maintenance/redis.go
Labels: enhancement

#195 Refactor time of day in maintenance
  apis/vshn/v1/common_types.go
  apis/vshn/v1/common_types_test.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/common/schedule.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
  pkg/comp-functions/functions/vshnpostgres/schedule_test.go
Labels: enhancement

#194 Fix hardcoded servicename
  pkg/comp-functions/functions/common/instance_namespace.go
Labels: bug

#199 Fix a bug, where you can't edit an existing VSHNPostgreSQL instance
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  test/functions/vshn-postgres/secrets/02_input_function-io.yaml
Labels: bug

#197 Add feature to allow setting a custom configuration for keycloak
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
Labels: enhancement

#200 Fix connection detail name
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: bug

#202 Add backups for nextcloud
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/vshnmariadb/backup.go
  pkg/comp-functions/functions/vshnnextcloud/backup.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
  pkg/comp-functions/functions/vshnnextcloud/files/backup.sh
  pkg/comp-functions/functions/vshnnextcloud/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/register.go
Labels: enhancement

#204 Add PDB
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  hack/bootstrap/template/api.txt
  pkg/comp-functions/functions/common/alerting.go
  pkg/comp-functions/functions/common/interfaces.go
  pkg/comp-functions/functions/common/pdb.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/register.go
  pkg/comp-functions/functions/vshnminio/register.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/scheme.go
Labels: enhancement

#203 Implement deletionProtection for claims
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  cmd/controller.go
  config/controller/cluster-role.yaml
  config/controller/webhooks.yaml
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_vshnminios.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnminios.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnredis.yaml
  hack/bootstrap/template.go
  hack/bootstrap/template/api.txt
  hack/bootstrap/template/webhook.txt
  pkg/comp-functions/functions/common/interfaces.go
  pkg/comp-functions/runtime/naming.go
  pkg/controller/postgres/deletion_protection.go
  pkg/controller/postgres/deletion_protection_test.go
  pkg/controller/postgres/reconciler.go
  pkg/controller/postgres/reconciler_test.go
  pkg/controller/webhooks/claim_deletionprotection.go
  pkg/controller/webhooks/default_handler.go
  pkg/controller/webhooks/default_handler_test.go
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/mariadb.go
  pkg/controller/webhooks/minio.go
  pkg/controller/webhooks/nextcloud.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/controller/webhooks/redis.go
  pkg/controller/webhooks/redis_test.go
Labels: enhancement

#208 Fix wrong probe path for keycloak for the sli exporter
  pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
Labels: bug

#209 Add deletionProtection for ObjectBuckets
  apis/v1/objectstorage_types.go
  apis/v1/zz_generated.deepcopy.go
  cmd/controller.go
  config/controller/webhooks.yaml
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  pkg/controller/webhooks/objectbuckets.go
  pkg/controller/webhooks/xobjectbuckets.go
Labels: enhancement
