Repository vshn/appcat, pull requests merged in 2024-11, with the labels that each got.

#249 Add MariaDB Scaling
  apis/vshn/v1/dbaas_vshn_mariadb.go
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
  pkg/comp-functions/functions/common/resources.go
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/files/proxysql.conf.tmpl
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy_test.go
  pkg/comp-functions/functions/vshnmariadb/proxysql.go
  pkg/comp-functions/functions/vshnmariadb/proxysql_test.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/webhooks/mariadb.go
Labels: minor

#259 Fix typo in the usage protecting the instance NS
  pkg/comp-functions/functions/vshnmariadb/user_management.go
Labels: patch

#260 Support Postgres 17
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
Labels: enhancement, patch

#245 Nextcloud collabora
  apis/vshn/v1/vshn_nextcloud.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  pkg/comp-functions/functions/common/rbac.go
  pkg/comp-functions/functions/vshnnextcloud/billing.go
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
  pkg/comp-functions/functions/vshnnextcloud/collabora_test.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/files/coolkit.xml
  pkg/comp-functions/functions/vshnnextcloud/files/coolwsd.xml
  pkg/comp-functions/functions/vshnnextcloud/files/install-collabora.sh
  pkg/comp-functions/functions/vshnnextcloud/register.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/vshnnextcloud/01_default.yaml
Labels: enhancement, minor

#262 Re-write alerts so they work with cluster monitoring
  pkg/comp-functions/functions/common/nonsla/alerting.go
  pkg/comp-functions/functions/common/nonsla/alerting_test.go
  pkg/comp-functions/functions/common/nonsla/non_sla_prom_rules.go
  pkg/comp-functions/functions/vshnkeycloak/register.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/comp-functions/functions/vshnminio/register.go
  pkg/comp-functions/functions/vshnpostgres/alerts.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnredis/register.go
Labels: patch

#256 Implement webhook logic for split control-plane - service cluster setup
  cmd/controller.go
  pkg/comp-functions/functions/common/instance_namespace.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnpostgres/objectbucket.go
  pkg/comp-functions/functions/vshnredis/pvcresize.go
  pkg/comp-functions/functions/vshnredis/pvcresize_test.go
  pkg/comp-functions/functions/vshnredis/release.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/webhooks/deletionprotection.go
  pkg/controller/webhooks/deletionprotection_test.go
  pkg/controller/webhooks/generic_deletionprotection_handler.go
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/namespace.go
  pkg/controller/webhooks/object.go
  pkg/controller/webhooks/pvc.go
  pkg/controller/webhooks/release.go
  pkg/controller/webhooks/xobjectbuckets.go
Labels: enhancement, minor

#263 Allow rotation of the restart ops
  pkg/comp-functions/functions/vshnpostgres/restart.go
Labels: patch

#261 Prevent empty BackupNames from being referenced
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: patch

#264 Allow to disable PgBouncer in VSHNPostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: enhancement, minor

#267 Use a default client if controlPanel client is nil
  pkg/controller/webhooks/deletionprotection.go
Labels: patch

#268 Fix disable pg bouncer name parameter
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
Labels: bug, patch

#265 Add new custom pg exporter config
  pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnpostgres/scripts/queries.yml
Labels: patch

#271 Allow deletion of PDBs
  pkg/comp-functions/functions/common/pdb.go
Labels: patch

#272 Don't deploy billing prometheus rule for tests
  pkg/comp-functions/functions/common/billing.go
Labels: minor

#275 Add possibility to disable TLS in VSHNPostgreSQL
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/postgresql.go
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
Labels: enhancement, minor

#276 Hotfix: adding missing tls={} configuration to claim
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
Labels: bug, minor

#277 adding missing reference in vshnpostgresql claim
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
Labels: bug, minor
