Repository vshn/appcat, pull requests merged in 2024-09, with the labels that each got.

#221 Improve CI Pipeline on PRs
  .cruft.json
  .github/changelog-configuration.json
  .github/workflows/cruft-update.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  Makefile
  ci.mk
  kind/config.yaml
  kind/kind.mk
Labels: patch

#227 Small change to test CI again
  README.md
Labels: patch

#229 Fix operator upgrade restart instance
  apis/stackgres/v1/sgcluster.go
  pkg/comp-functions/functions/vshnpostgres/restart.go
Labels: bug, patch

#230 fixing PDB selector label
  apis/vshn/v1/dbaas_vshn_postgresql.go
Labels: bug, patch

#228 Remove old make targets
  Makefile
  package/package.mk
Labels: dependency

#225 Add support for SPKS and implement sts resizing
  Makefile
  apis/helm/release/v1beta1/types.go
  apis/syntools/generate.go
  apis/syntools/v1alpha1/compositeredisinstance.go
  apis/syntools/v1alpha1/compositermariadb.go
  apis/syntools/v1alpha1/groupversion_info.go
  apis/syntools/v1alpha1/zz_generated.deepcopy.go
  apis/syntools/v1alpha1/zz_generated.managed.go
  apis/syntools/v1alpha1/zz_generated.managedlist.go
  cmd/functions.go
  crds/vshn.appcat.vshn.io_compositemariadbinstances.yaml
  crds/vshn.appcat.vshn.io_compositeredisinstances.yaml
  pkg/comp-functions/functions/spksmariadb/pvcresize.go
  pkg/comp-functions/functions/spksmariadb/register.go
  pkg/comp-functions/functions/spksmariadb/script/recreate.sh
  pkg/comp-functions/functions/spksredis/pvcresize.go
  pkg/comp-functions/functions/spksredis/register.go
  pkg/comp-functions/functions/spksredis/script/recreate.sh
  pkg/scheme.go
Labels: enhancement, minor

#233 Fix ObjectBucket deletion protection
  Makefile
  apis/exoscale/v1/dbaas_exoscale_kafka.go
  apis/exoscale/v1/dbaas_exoscale_mysql.go
  apis/exoscale/v1/dbaas_exoscale_opensearch.go
  apis/exoscale/v1/dbaas_exoscale_postgresql.go
  apis/exoscale/v1/dbaas_exoscale_redis.go
  apis/exoscale/v1/zz_generated.deepcopy.go
  apis/v1/objectstorage_types.go
  apis/v1/zz_generated.deepcopy.go
  apis/vshn/v1/common_types_test.go
  apis/vshn/v1/conditions.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/objectreference.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/controller/webhooks/objectbuckets.go
  pkg/controller/webhooks/objectbuckets_test.go
  pkg/maintenance/postgresql_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: patch

#231 Add script to generate diffs between a cluster and the local branch
  .github/workflows/diff.yml
  .gitignore
  Makefile
  hack/diff/compare.sh
  hack/diff/function.yaml.tmpl
  main.go
  pkg/maintenance/postgresql_test.go
Labels: minor

#236 Fix dependency issue when using encrypted PVCs for VSHNPostgreSQL
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnpostgres/encrypted_pvc.go
  pkg/comp-functions/functions/vshnpostgres/encrypted_pvc_test.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/vshn-postgres/enc_pvc/03-GivenEncryptionParams.yaml
  test/functions/vshn-postgres/enc_pvc/03-GivenEncryptionParamsExistingSecret.yaml
Labels: bug, patch

#235 Improve PostgreSQL ordering, reduce issues
  apis/v1/objectstorage_types.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
  test/functions/vshn-postgres/deploy/01_default.yaml
  test/functions/vshn-postgres/deploy/02_with_pg_config.yaml
  test/functions/vshn-postgres/deploy/03_with_restore.yaml
Labels: bug, minor
