Repository vshn/appcat, pull requests merged in 2024-10, with the labels that each got.

#238 fixing bug in connection details
  pkg/comp-functions/functions/vshnpostgres/user_management.go
Labels: bug, patch

#237 Add providerConfig management
  Makefile
  README.md
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/explanations/providerconfig-management.adoc
  hack/diff/compare.sh
  hack/diff/function.yaml.tmpl
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/comp-functions/runtime/function_mgr_test.go
Labels: minor

#239 adding delayed removal of xobjectbucket
  pkg/controller/webhooks/xobjectbuckets.go
Labels: enhancement, patch

#241 Add support for PostgreSQL 16
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
Labels: enhancement, minor

#240 Add billing to services
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/non_gen_types.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  pkg/comp-functions/functions/common/billing.go
  pkg/comp-functions/functions/common/interfaces.go
  pkg/comp-functions/functions/vshnkeycloak/billing.go
  pkg/comp-functions/functions/vshnkeycloak/register.go
  pkg/comp-functions/functions/vshnmariadb/billing.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/comp-functions/functions/vshnminio/billing.go
  pkg/comp-functions/functions/vshnminio/register.go
  pkg/comp-functions/functions/vshnnextcloud/billing.go
  pkg/comp-functions/functions/vshnnextcloud/register.go
  pkg/comp-functions/functions/vshnpostgres/billing.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnredis/billing.go
  pkg/comp-functions/functions/vshnredis/register.go
Labels: bug, patch

#242 Fix backups if Redis TLS is disabled
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/functions/vshnredis/script/backup.sh
Labels: bug, patch

#247 Add initcontainer to wait for PostgreSQL
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: patch

#246 Refactor billing
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/dbaas_vshn_redis.go
  apis/vshn/v1/vshn_minio.go
  apis/vshn/v1/vshn_nextcloud.go
  pkg/comp-functions/functions/common/billing.go
  pkg/comp-functions/functions/common/instance_namespace.go
  pkg/comp-functions/functions/common/interfaces.go
  pkg/comp-functions/functions/vshnkeycloak/billing.go
  pkg/comp-functions/functions/vshnmariadb/billing.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnminio/billing.go
  pkg/comp-functions/functions/vshnnextcloud/billing.go
  pkg/comp-functions/functions/vshnpostgres/billing.go
  pkg/comp-functions/functions/vshnredis/billing.go
Labels: bug, enhancement, minor

#250 Remove custom pg exporter queries
  pkg/comp-functions/functions/vshnpostgres/files/queries.yml
  pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go
  pkg/comp-functions/functions/vshnpostgres/register.go
Labels: patch

#253 Add possibility to run MariaDB without TLS
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
Labels: enhancement, minor

#254 Fix pg config
  pkg/comp-functions/functions/vshnkeycloak/billing.go
  pkg/comp-functions/functions/vshnkeycloak/register.go
  pkg/comp-functions/functions/vshnmariadb/billing.go
  pkg/comp-functions/functions/vshnmariadb/register.go
  pkg/comp-functions/functions/vshnminio/billing.go
  pkg/comp-functions/functions/vshnminio/register.go
  pkg/comp-functions/functions/vshnnextcloud/billing.go
  pkg/comp-functions/functions/vshnnextcloud/register.go
  pkg/comp-functions/functions/vshnpostgres/billing.go
  pkg/comp-functions/functions/vshnpostgres/extensions.go
  pkg/comp-functions/functions/vshnpostgres/extensions_test.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnredis/billing.go
  pkg/comp-functions/functions/vshnredis/register.go
Labels: bug, patch

#255 Fix pg-conf naming issues
  pkg/comp-functions/functions/vshnpostgres/delay_cluster.go
  pkg/comp-functions/functions/vshnpostgres/extensions.go
  pkg/comp-functions/functions/vshnpostgres/extensions_test.go
  test/functions/vshn-postgres/delay_cluster/01_GivenAllDependencies.yaml
  test/functions/vshn-postgres/extensions/01-GivenAlreadyEnabled.yaml
  test/functions/vshn-postgres/extensions/01-GivenFreshConfig.yaml
Labels: patch

#244 Add deletionProtection for managed crossplane resources
  Makefile
  apis/kubernetes/v1alpha1/doc.go
  apis/kubernetes/v1alpha1/management_policy_hack.go
  apis/kubernetes/v1alpha1/register.go
  apis/kubernetes/v1alpha1/types.go
  apis/kubernetes/v1alpha1/zz_generated.deepcopy.go
  apis/syntools/v1alpha1/compositermariadbdatabaseinstance.go
  apis/syntools/v1alpha1/compositermariadbinstance.go
  apis/syntools/v1alpha1/compositermariadbuserinstance.go
  apis/syntools/v1alpha1/groupversion_info.go
  apis/syntools/v1alpha1/zz_generated.deepcopy.go
  apis/syntools/v1alpha1/zz_generated.managed.go
  apis/syntools/v1alpha1/zz_generated.managedlist.go
  cmd/controller.go
  config/controller/cluster-role.yaml
  config/controller/webhooks.yaml
  crds/vshn.appcat.vshn.io_compositemariadbdatabaseinstances.yaml
  crds/vshn.appcat.vshn.io_compositemariadbuserinstances.yaml
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/postgres/deletion_protection.go
  pkg/controller/postgres/deletion_protection_test.go
  pkg/controller/postgres/reconciler.go
  pkg/controller/postgres/reconciler_test.go
  pkg/controller/webhooks/generic_deletionprotection_handler.go
  pkg/controller/webhooks/mysql.go
  pkg/controller/webhooks/namespace.go
  pkg/controller/webhooks/object.go
  pkg/controller/webhooks/release.go
  pkg/scheme.go
Labels: enhancement, minor

#257 Remove v1alpha1 for objects from webhook definition
  config/controller/webhooks.yaml
  pkg/controller/webhooks/object.go
Labels: bug, patch
