Repository vshn/appcat, pull requests merged in 2025-07, with the labels that each got.

#379 Keycloak: Copy custom files from customization image
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/comp-functions/functions/vshnkeycloak/templates/copy-custom-files.tmpl
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/keycloak_test.go
Labels: enhancement, minor

#401 VSHNKeycloak: Fix bug with custom files
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
Labels: bug, patch, ignoreChangelog

#400 Release appcat
  .cruft.json
  .github/changelog-configuration.json
  .github/workflows/pr.yml
  README.md
  apis/apiserver/v1/generated.pb.go
  apis/apiserver/v1/vshn_nextcloud_backup_types.go
  apis/sql/postgresql/v1alpha1/extension_types.go
  apis/sql/postgresql/v1alpha1/grant_types.go
  apis/sql/postgresql/v1alpha1/schema_types.go
  apis/sql/postgresql/v1alpha1/zz_generated.deepcopy.go
  apis/sql/postgresql/v1alpha1/zz_generated.managed.go
  apis/sql/postgresql/v1alpha1/zz_generated.managedlist.go
  apis/sql/postgresql/v1alpha1/zz_generated.resolvers.go
  apis/vshn/v1/dbaas_vshn_forgejo.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/vshn_nextcloud.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/apiserver/vshn/keycloak/get.go
  pkg/apiserver/vshn/keycloak/table.go
  pkg/apiserver/vshn/nextcloud/get.go
  pkg/apiserver/vshn/nextcloud/list.go
  pkg/apiserver/vshn/nextcloud/table.go
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/common/netpol.go
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/vshnforgejo/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/comp-functions/functions/vshnkeycloak/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/scripts/copy-kc-creds.sh
  pkg/comp-functions/functions/vshnkeycloak/templates/copy-custom-files.tmpl
  pkg/comp-functions/functions/vshnmariadb/maintenance.go
  pkg/comp-functions/functions/vshnminio/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/backup.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/billing.go
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  pkg/comp-functions/functions/vshnpostgres/connection_details_test.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/scripts/copy-pg-backup.sh
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/comp-functions/functions/vshnredis/script/prepRestore.sh
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/keycloak_test.go
  pkg/openapi/generated.openapi.go
  test/functions/vshn-postgres/base.yaml
  test/functions/vshnforgejo/01_default.yaml
Labels: minor, ignoreChangelog

#409 Remove obsolete volumeMount
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
Labels: patch, ignoreChangelog, hotfix

#418 Allow deletion of the Keycloak config apply job
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
Labels: bug, minor, ignoreChangelog, hotfix

#422 Revert "Add support for Redis HA"
  apis/vshn/v1/dbaas_vshn_redis.go
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  crds/vshn.appcat.vshn.io_xvshnredis.yaml
  pkg/comp-functions/functions/vshnredis/redis_deploy.go
  pkg/comp-functions/functions/vshnredis/script/scaling.sh
Labels: patch, ignoreChangelog

#394 Add `envFrom` field to VSHNKeycloak
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/controller/webhooks/keycloak.go
  test/functions/vshnkeycloak/01_default.yaml
Labels: minor

#425 Ensure Keycloak Config Apply Job Executes on Initial Install
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/controller/webhooks/keycloak.go
  test/functions/vshnkeycloak/01_default.yaml
Labels: bug, minor, hotfix

#431 Fix race conditions due to desiredComposite
  pkg/comp-functions/functions/vshnforgejo/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/maintenance.go
  pkg/comp-functions/functions/vshnmariadb/maintenance.go
  pkg/comp-functions/functions/vshnmariadb/proxysql.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnmariadb/user_management_test.go
  pkg/comp-functions/functions/vshnminio/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/comp-functions/runtime/function_mgr.go
Labels: patch, ignoreChangelog, hotfix

#432 Merge Master to Develop
  pkg/comp-functions/functions/vshnforgejo/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/maintenance.go
  pkg/comp-functions/functions/vshnmariadb/maintenance.go
  pkg/comp-functions/functions/vshnmariadb/proxysql.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnmariadb/user_management_test.go
  pkg/comp-functions/functions/vshnminio/maintenance.go
  pkg/comp-functions/functions/vshnnextcloud/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/comp-functions/runtime/function_mgr.go
Labels: patch, ignoreChangelog

#433 Fixing some race conditions and e2e
  pkg/comp-functions/functions/common/instance_namespace.go
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/common/billing.yaml
Labels: patch

#435 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
