Repository vshn/appcat, pull requests merged in 2025-08, with the labels that each got.

#438 Switch Bitnami images to legacy registry
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnredis/pvcresize.go
  pkg/comp-functions/functions/vshnredis/redis_deploy.go
  pkg/comp-functions/functions/vshnredis/restore.go
  pkg/maintenance/forgejo.go
  pkg/maintenance/keycloak.go
  pkg/maintenance/mariadb.go
  pkg/maintenance/minio.go
  pkg/maintenance/nextcloud.go
  pkg/maintenance/redis.go
  pkg/maintenance/redis_test.go
  pkg/maintenance/url.go
Labels: minor, ignoreChangelog, hotfix

#441 Fix Redis restore and pvc resize
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/functions/vshnredis/pvcresize.go
  pkg/comp-functions/functions/vshnredis/pvcresize_test.go
  pkg/comp-functions/functions/vshnredis/restore.go
  pkg/comp-functions/functions/vshnredis/script/cleanupRestore.sh
  pkg/comp-functions/functions/vshnredis/script/prepRestore.sh
  pkg/comp-functions/functions/vshnredis/script/recreate.sh
  pkg/comp-functions/functions/vshnredis/script/restore.sh
  test/functions/vshnredis/pvcresize/01_default.yaml
  test/functions/vshnredis/pvcresize/01_job.yaml
  test/functions/vshnredis/restore/01-GivenNoRestoreConfig.yaml
  test/functions/vshnredis/restore/01-GivenRestoreConfig.yaml
  test/functions/vshnredis/restore/01-GivenRestoreConfigNoBN.yaml
  test/functions/vshnredis/restore/01-GivenRestoreConfigNoCN.yaml
Labels: bug, minor, hotfix

#446 Fix bug in UserManagement if username != dbname
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
Labels: bug, patch

#450 Validate VSHNPG encryption state
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/keycloak_test.go
  pkg/controller/webhooks/nextcloud.go
  pkg/controller/webhooks/nextcloud_test.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
Labels: bug, minor

#452 Removed omitempty from default=true boolean fields
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
Labels: bug, minor

#457 Fixed long startup times on nextcloud via security contexts
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: bug, minor

#451 Expand maintenance window
  pkg/comp-functions/functions/common/schedule.go
  pkg/comp-functions/functions/common/schedule_test.go
  pkg/comp-functions/functions/vshnpostgres/schedule_test.go
Labels: patch

#458 Fix some more bugs with user provisioning
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/runtime/function_mgr.go
Labels: patch

#459 🔀 Merge develop into master (Release)
  .github/workflows/merge.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  apis/vshn/v1/common_types.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/common/schedule.go
  pkg/comp-functions/functions/common/schedule_test.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnpostgres/schedule_test.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/webhooks/keycloak.go
  pkg/controller/webhooks/keycloak_test.go
  pkg/controller/webhooks/nextcloud.go
  pkg/controller/webhooks/nextcloud_test.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
Labels: minor, ignoreChangelog

#462 Check generated secrets by fields
  .github/workflows/merge.yml
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/common/password_test.go
Labels: patch, hotfix

#463 Fixed permission denied error for nextcloud backups
  pkg/comp-functions/functions/vshnnextcloud/files/backup.sh
Labels: bug, patch
