Repository vshn/appcat, pull requests merged in 2025-02, with the labels that each got.

#304 Add note on devcontainer building
  README.md
Labels: documentation

#296 Make connection details split cluster compatible
  .devcontainer/devcontainer.json
  Makefile
  apis/vshn/v1/dbaas_vshn_mariadb.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
  crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
  pkg/comp-functions/functions/buckets/cloudscalebucket/cloudscalebucket.go
  pkg/comp-functions/functions/buckets/exoscalebucket/exoscalebucket.go
  pkg/comp-functions/functions/buckets/miniobucket/miniobucket.go
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/common/instance_namespace.go
  pkg/comp-functions/functions/common/mailgun_alerting.go
  pkg/comp-functions/functions/common/netpol.go
  pkg/comp-functions/functions/common/password.go
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/common/release.go
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnmariadb/proxysql.go
  pkg/comp-functions/functions/vshnmariadb/proxysql_test.go
  pkg/comp-functions/functions/vshnmariadb/user_management.go
  pkg/comp-functions/functions/vshnmariadb/user_management_test.go
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnminio/providerconfig.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  pkg/comp-functions/functions/vshnpostgres/loadBalancer.go
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/vshnmariadb/01-user-management.yaml
Labels: minor

#297 Add new VSHNForgejo Service
  Makefile
  apis/codey/dbaas_vshn_codey.go
  apis/codey/generate.go
  apis/codey/groupversion_info.go
  apis/codey/zz_generated.deepcopy.go
  apis/codey/zz_generated.managed.go
  apis/codey/zz_generated.managedlist.go
  apis/vshn/v1/dbaas_vshn_forgejo.go
  apis/vshn/v1/groupversion_info.go
  apis/vshn/v1/zz_generated.deepcopy.go
  apis/vshn/v1/zz_generated.managed.go
  apis/vshn/v1/zz_generated.managedlist.go
  cmd/controller.go
  cmd/functions.go
  crds/codey.io_codeyinstances.yaml
  crds/codey.io_xcodeyinstances.yaml
  crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
  go.mod
  go.sum
  hack/bootstrap/examples/tmpl.json
  hack/bootstrap/template.go
  hack/bootstrap/template/api.txt
  hack/bootstrap/template/webhook.txt
  pkg/comp-functions/functions/common/release.go
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnforgejo/register.go
Labels: enhancement, minor

#306 updating function call updated in other branch
  pkg/comp-functions/functions/vshnforgejo/deploy.go
Labels: bug, patch

#308 Fix typo in sslMode for provider-sql
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  pkg/comp-functions/functions/vshnpostgres/user_management_test.go
Labels: bug, patch

#309 fixing label selector for our loadbalancer services in vshnpostgresql
  pkg/comp-functions/functions/vshnpostgres/loadBalancer.go
Labels: bug, patch

#292 Postgres major upgrade support
  Makefile
  apis/stackgres/v1/sgdbops.gen.go
  apis/stackgres/v1/sgdbops.yaml
  apis/stackgres/v1/zz_generated.deepcopy.go
  apis/stackgres/v1beta1/sgobjectstorage.gen.go
  apis/stackgres/v1beta1/sgobjectstorage.yaml
  apis/stackgres/v1beta1/sgobjectstorage_crd.yaml
  apis/stackgres/v1beta1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  cmd/maintenance.go
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/auth/http.go
  pkg/auth/stackgres/client.go
  pkg/auth/stackgres/client_test.go
  pkg/comp-functions/functions/vshnpostgres/delay_cluster.go
  pkg/comp-functions/functions/vshnpostgres/load_balancer.go
  pkg/comp-functions/functions/vshnpostgres/load_balancer_test.go
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/major_version_upgrade.go
  pkg/comp-functions/functions/vshnpostgres/major_version_upgrade_test.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/comp-functions/functions/vshnpostgres/restart.go
  pkg/comp-functions/runtime/function_mgr.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/postgresql_test.go
Labels: minor

#311 Fix postgres webhook to allow major upgrade when non HA
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
Labels: bug, patch

#310 Add Forgejo backup
  apis/vshn/v1/dbaas_vshn_forgejo.go
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/common/schedule.go
  pkg/comp-functions/functions/vshnforgejo/backup.go
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnforgejo/register.go
  pkg/comp-functions/functions/vshnforgejo/script/backup.sh
Labels: enhancement, minor

#316 Use separate observer for root password
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
Labels: patch

#317 Re-add password for URL generation
  pkg/comp-functions/functions/vshnpostgres/connection_details.go
  pkg/comp-functions/functions/vshnpostgres/connection_details_test.go
  pkg/comp-functions/functions/vshnpostgres/user_management.go
  test/functions/vshn-postgres/secrets/02_input_function-io.yaml
Labels: patch
