Repository vshn/appcat, pull requests merged in 2025-09, with the labels that each got.

#466 Redis HA alerting
  cmd/sliexporter.go
  pkg/sliexporter/probes/common.go
  pkg/sliexporter/probes/http.go
  pkg/sliexporter/probes/http_test.go
  pkg/sliexporter/probes/maintenance_ctx.go
  pkg/sliexporter/probes/manager.go
  pkg/sliexporter/probes/manager_test.go
  pkg/sliexporter/probes/mariadb.go
  pkg/sliexporter/probes/minio.go
  pkg/sliexporter/probes/minio_test.go
  pkg/sliexporter/probes/postgresql.go
  pkg/sliexporter/probes/postgresql_test.go
  pkg/sliexporter/probes/redis.go
  pkg/sliexporter/sli_reconciler/reconciler.go
  pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
  pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller.go
  pkg/sliexporter/vshnminio_controller/vshnminio_controller_test.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
  pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
Labels: minor

#471 Update psql stackgres queries to the latest version
  pkg/comp-functions/functions/vshnpostgres/scripts/queries.yml
Labels: bug, patch

#474 Add nextcloud scc
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: patch

#491 Add RBAC for providerconfig checks
  config/controller/cluster-role.yaml
  pkg/controller/webhooks/default_handler.go
Labels: patch
