Repository vshn/appcat, pull requests merged in 2025-01, with the labels that each got.

#288 Add support for devcontainers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .gitignore
  Makefile
  README.md
Labels: minor

#283 Switch instances monitoring from cluster to user-workload monitoring
  pkg/comp-functions/functions/common/billing.go
  pkg/comp-functions/functions/common/instance_namespace.go
Labels: minor

#290 Add image repository parameter, to be able to override the registry
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: bug, patch

#289 Add sidecar for nextcloud cron jobs
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: bug, patch

#295 Fix typo in stackgres resource
  apis/helm/release/v1alpha1/types.go
  apis/stackgres/v1/groupversion_info.go
  apis/stackgres/v1/sginstanceprofile.go
  apis/stackgres/v1/sgpostresconfig.go
  apis/stackgres/v1/zz_generated.deepcopy.go
Labels: patch

#299 Fix nextcloud workload
  apis/vshn/v1/vshn_nextcloud.go
Labels: bug, patch

#300 Replace `gcr.io` `kube-rbac-proxy` image
  config/sliexporter/default/manager_auth_proxy_patch.yaml
Labels: dependency

#298 Set image registry and repository
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: minor

#301 Fix nextcloud image registry
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: patch

#302 Add support for Kafka 3.8
  apis/exoscale/v1/dbaas_exoscale_kafka.go
  crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
Labels: bug, patch
