Repository vshn/appcat, pull requests merged in 2025-06, with the labels that each got.

#354 Forgejo/Codey: Set compute resources according to plans
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnforgejo/deploy_test.go
  pkg/controller/webhooks/codey.go
  test/functions/vshnforgejo/01_default.yaml
Labels: enhancement, minor

#368 Keycloak by VSHN list PostgreSQL backups via APIserver
  apis/apiserver/v1/generated.pb.go
  apis/apiserver/v1/register.go
  apis/apiserver/v1/vshn_keycloak_backup_types.go
  apis/apiserver/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/apiserver.go
  config/apiserver/role.yaml
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/apiserver/common.go
  pkg/apiserver/vshn/keycloak/backup.go
  pkg/apiserver/vshn/keycloak/get.go
  pkg/apiserver/vshn/keycloak/list.go
  pkg/apiserver/vshn/keycloak/list_test.go
  pkg/apiserver/vshn/keycloak/table.go
  pkg/apiserver/vshn/keycloak/vshnkeycloak.go
  pkg/openapi/generated.openapi.go
Labels: enhancement, minor

#366 Permanently disable Envoy
  apis/stackgres/v1/sgcluster.gen.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: minor

#363 Move Redis from P&T to comp-functions
  pkg/comp-functions/functions/vshnredis/backup.go
  pkg/comp-functions/functions/vshnredis/backup_test.go
  pkg/comp-functions/functions/vshnredis/redis_deploy.go
  pkg/comp-functions/functions/vshnredis/redis_deploy_test.go
  pkg/comp-functions/functions/vshnredis/redis_url.go
  pkg/comp-functions/functions/vshnredis/redis_url_test.go
  pkg/comp-functions/functions/vshnredis/register.go
  pkg/comp-functions/functions/vshnredis/release.go
  pkg/comp-functions/functions/vshnredis/release_test.go
  pkg/comp-functions/functions/vshnredis/tls.go
  test/functions/vshnredis/deploy/01_default.yaml
Labels: enhancement, minor

#370 Fix 'open-pr-component' action
  .github/workflows/pr.yml
Labels: bug, patch

#371 Fix wrong pitr configuration
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
  test/functions/vshn-postgres/deploy/03_with_restore.yaml
Labels: bug, patch

#374 Revert back to try'n error approach for maintenance
  cmd/hotfixreleaser.go
  pkg/maintenance/release/release.go
Labels: patch

#376 Run diff against latest version on the cluster
  hack/diff/compare.sh
Labels: patch

#373 Support mounting secrets and configmaps as volumes in VSHNKeycloak
  apis/stackgres/v1/zz_generated.deepcopy.go
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/runtime/function_mgr.go
Labels: enhancement, minor

#381 Enable Gitflow
  .cruft.json
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr.yml
Labels: minor

#382 Only trigger release on master
  .cruft.json
  .github/workflows/pr.yml
Labels: patch

#375 Add automated restore for Keycloak
  apis/vshn/v1/dbaas_vshn_keycloak.go
  apis/vshn/v1/dbaas_vshn_postgresql.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/apiserver/vshn/keycloak/get.go
  pkg/apiserver/vshn/keycloak/table.go
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnkeycloak/scripts/copy-kc-creds.sh
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/scripts/copy-pg-backup.sh
  test/functions/vshn-postgres/base.yaml
Labels: minor

#391 Keycloak metrics. Appcat's Own ServiceMonitor.
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
Labels: enhancement, minor, ignoreChangelog

#397 Hotfix clear ownerReferences when copying kube-objects
  pkg/comp-functions/runtime/function_mgr.go
Labels: bug, minor, hotfix

#395 Helm Chart updates June 2025
  apis/vshn/v1/dbaas_vshn_forgejo.go
  apis/vshn/v1/vshn_nextcloud.go
  crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  test/functions/vshnforgejo/01_default.yaml
Labels: minor, ignoreChangelog
