Repository vshn/appcat, pull requests merged in 2025-04, with the labels that each got.

#339 Set latest version of pg_repack extension
  pkg/comp-functions/functions/vshnpostgres/extensions.go
  pkg/comp-functions/functions/vshnpostgres/extensions_test.go
Labels: minor

#341 Improve responsiveness with high poll interval
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
  pkg/comp-functions/functions/vshnpostgres/restart.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/vshn-postgres/restart/03-KeepRecentReboots.yaml
Labels: minor

#340 Add support for ingress labels
  pkg/comp-functions/functions/common/ingress.go
Labels: enhancement, minor

#327 Add non-converged setup support for the API server
  go.mod
  go.sum
  pkg/apiserver/appcat/appcat.go
  pkg/apiserver/common.go
  pkg/apiserver/vshn/k8up/k8up.go
  pkg/apiserver/vshn/mariadb/backup.go
  pkg/apiserver/vshn/mariadb/common_test.go
  pkg/apiserver/vshn/mariadb/get.go
  pkg/apiserver/vshn/mariadb/get_test.go
  pkg/apiserver/vshn/mariadb/list.go
  pkg/apiserver/vshn/mariadb/list_test.go
  pkg/apiserver/vshn/mariadb/vshnmariadb.go
  pkg/apiserver/vshn/mariadb/watch.go
  pkg/apiserver/vshn/nextcloud/backup.go
  pkg/apiserver/vshn/nextcloud/get.go
  pkg/apiserver/vshn/nextcloud/list.go
  pkg/apiserver/vshn/nextcloud/list_test.go
  pkg/apiserver/vshn/nextcloud/vshnnextcloud.go
  pkg/apiserver/vshn/postgres/backup.go
  pkg/apiserver/vshn/postgres/backup_test.go
  pkg/apiserver/vshn/postgres/get.go
  pkg/apiserver/vshn/postgres/get_test.go
  pkg/apiserver/vshn/postgres/list.go
  pkg/apiserver/vshn/postgres/list_test.go
  pkg/apiserver/vshn/postgres/sgbackups.go
  pkg/apiserver/vshn/postgres/vshnpostgresql.go
  pkg/apiserver/vshn/postgres/vshnpostgresql_test.go
  pkg/apiserver/vshn/redis/backup.go
  pkg/apiserver/vshn/redis/common_test.go
  pkg/apiserver/vshn/redis/get.go
  pkg/apiserver/vshn/redis/get_test.go
  pkg/apiserver/vshn/redis/list.go
  pkg/apiserver/vshn/redis/list_test.go
  pkg/apiserver/vshn/redis/vshnredis.go
  pkg/apiserver/vshn/redis/watch.go
  test/mocks/mock_client.go
  test/mocks/mock_sgbackups.go
  test/mocks/mock_vshnpostgresqls.go
Labels: enhancement, minor

#343 Enable HA for MariaDB in SLI exporter
  pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go
  pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
Labels: minor

#345 Add default forgejo admin email
  pkg/comp-functions/functions/vshnforgejo/deploy.go
Labels: minor

#342 Switch backups to use the default region
  apis/v1/objectstorage_types.go
  crds/appcat.vshn.io_objectbuckets.yaml
  crds/appcat.vshn.io_xobjectbuckets.yaml
  pkg/comp-functions/functions/buckets/exoscalebucket/exoscalebucket.go
  pkg/comp-functions/functions/common/backup/backup.go
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: minor

#346 Add Forgejo host connection detail
  pkg/comp-functions/functions/vshnforgejo/deploy.go
Labels: patch

#347 Don't test the URL uniqueness against itself
  Makefile
  README.md
  apis/codey/dbaas_vshn_codey.go
  apis/codey/zz_generated.deepcopy.go
  crds/codey.io_codeyinstances.yaml
  pkg/controller/webhooks/codey.go
Labels: patch
