Repository vshn/appcat, pull requests merged in 2025-05, with the labels that each got.

#353 disabling majorVersionUpgrades
  apis/vshn/v1/dbaas_vshn_postgresql.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
  pkg/comp-functions/functions/vshnpostgres/register.go
  pkg/controller/webhooks/postgresql.go
  pkg/controller/webhooks/postgresql_test.go
Labels: bug, minor

#352 Fix Nextcloud default PG settings
  pkg/comp-functions/functions/common/postgresql.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
Labels: minor

#351 Add hotfix release job
  cmd/hotfixreleaser.go
  cmd/maintenance.go
  main.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/maintenance/release/release.go
  pkg/maintenance/release/release_test.go
Labels: minor

#355 Add Version to CollaboraSpec
  apis/vshn/v1/vshn_nextcloud.go
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
  pkg/comp-functions/functions/vshnnextcloud/collabora_test.go
  pkg/comp-functions/functions/vshnnextcloud/deploy.go
  test/functions/vshnnextcloud/01_default.yaml
  test/functions/vshnnextcloud/01_no_fqdn.yaml
Labels: enhancement, minor

#356 Helm Chart updates May 2025
  apis/vshn/v1/dbaas_vshn_redis.go
  crds/vshn.appcat.vshn.io_vshnredis.yaml
  crds/vshn.appcat.vshn.io_xvshnredis.yaml
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/functions/vshnminio/minio_deploy.go
Labels: minor

#359 reenabling Keycloak service monitors
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
Labels: enhancement, minor

#357 Add missing roles for APIServer
  config/apiserver/role.yaml
  pkg/apiserver/appcat/appcat.go
  pkg/apiserver/vshn/mariadb/get.go
  pkg/apiserver/vshn/mariadb/list.go
  pkg/apiserver/vshn/nextcloud/get.go
  pkg/apiserver/vshn/nextcloud/list.go
  pkg/apiserver/vshn/postgres/get.go
  pkg/apiserver/vshn/postgres/list.go
  pkg/apiserver/vshn/redis/get.go
  pkg/apiserver/vshn/redis/list.go
Labels: enhancement, patch

#362 Fix wrong mailgun secret ref for patching secret
  pkg/comp-functions/functions/common/mailgun_alerting.go
Labels: bug, patch

#360 Make AppCat realtime compatible
  pkg/comp-functions/runtime/function_mgr.go
Labels: patch

#358 Forgejo mailer
  apis/vshn/v1/dbaas_vshn_forgejo.go
  apis/vshn/v1/zz_generated.deepcopy.go
  crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
Labels: enhancement, minor

#361 Enable Function Revisions
  cmd/hotfixreleaser.go
  cmd/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/maintenance/release/release.go
  pkg/maintenance/release/release_test.go
Labels: minor

#367 Ensure to fetch whole git history
  .github/workflows/pr.yml
Labels: patch
