Repository vshn/appcat, pull requests merged in 2025-03, with the labels that each got.

#313 Update CRD validation for Keycloak 26
  apis/vshn/v1/dbaas_vshn_keycloak.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
Labels: minor

#321 Also check for non empty value when waiting for connection details
  pkg/comp-functions/runtime/function_mgr.go
Labels: patch

#318 Fix a bug where unmanaged objects aren't protected
  .devcontainer/postCreateCommand.sh
  Makefile
  pkg/controller/webhooks/deletionprotection.go
Labels: patch

#315 Forgejo: Add maintenance
  cmd/maintenance.go
  pkg/comp-functions/functions/vshnforgejo/backup.go
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnforgejo/maintenance.go
  pkg/comp-functions/functions/vshnforgejo/register.go
  pkg/maintenance/forgejo.go
  pkg/maintenance/helm/helmpatcher.go
Labels: enhancement, minor

#323 Protect the certificate by the cluster
  pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
Labels: patch

#322 Collabora: Fix perpetual RSA key regeneration
  pkg/comp-functions/functions/vshnnextcloud/collabora.go
Labels: bug, patch

#326 adding diff check for CRDS/ directory
  .github/workflows/diff.yml
  Makefile
  crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
  crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
Labels: enhancement, minor

#328 Fix ingress using wrong service names
  apis/vshn/v1/dbaas_vshn_forgejo.go
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnnextcloud/ingress.go
Labels: bug, minor

#325 Forgejo customization
  apis/vshn/v1/dbaas_vshn_forgejo.go
  apis/vshn/v1/zz_generated.deepcopy.go
  cmd/controller.go
  config/controller/cluster-role.yaml
  config/controller/webhooks.yaml
  crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
  crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
  pkg/comp-functions/functions/vshnforgejo/deploy.go
  pkg/comp-functions/functions/vshnforgejo/deploy_test.go
  pkg/controller/webhooks/forgejo.go
  test/functions/vshnforgejo/01_default.yaml
Labels: enhancement, minor

#331 Forgejo: Fix ROOT_URL
  pkg/comp-functions/functions/vshnforgejo/deploy.go
Labels: bug, patch

#329 Add TLS for SPKS Redis 7
  apis/syntools/v1alpha1/compositeredisinstance.go
  apis/syntools/v1alpha1/zz_generated.deepcopy.go
  cmd/functions.go
  crds/vshn.appcat.vshn.io_compositeredisinstances.yaml
  go.mod
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/spks/common/ignore-connectiondetails.go
  pkg/comp-functions/functions/spks/spksmariadb/pvcresize.go
  pkg/comp-functions/functions/spks/spksmariadb/register.go
  pkg/comp-functions/functions/spks/spksmariadb/script/recreate.sh
  pkg/comp-functions/functions/spks/spksredis/pvcresize.go
  pkg/comp-functions/functions/spks/spksredis/register.go
  pkg/comp-functions/functions/spks/spksredis/script/recreate.sh
  pkg/comp-functions/functions/spks/spksredis/tls.go
  pkg/comp-functions/functions/spks/spksredis/tls_test.go
  pkg/comp-functions/functions/vshnkeycloak/deploy.go
  pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
  pkg/comp-functions/runtime/function_mgr.go
  test/functions/spksredis/01-scaleRedis.yaml
  test/functions/spksredis/02-scaleRedisFinished.yaml
  test/functions/spksredis/empty.yaml
Labels: minor

#334 Adjust default version for Keycloak
  apis/vshn/v1/dbaas_vshn_keycloak.go
  crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
  crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
Labels: minor

#332 Check Codey FQDN uniqueness
  apis/codey/dbaas_vshn_codey.go
  cmd/controller.go
  config/controller/cluster-role.yaml
  config/controller/webhooks.yaml
  pkg/controller/webhooks/codey.go
  pkg/scheme.go
Labels: enhancement, minor

#337 Fix nilpointer
  pkg/comp-functions/functions/common/tls.go
  pkg/comp-functions/functions/common/tls_test.go
  pkg/sliexporter/probes/postgresql_test.go
Labels: patch

#330 Add appcat release management in maintenance
  cmd/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance.go
  pkg/comp-functions/functions/common/maintenance/maintenance_test.go
  pkg/comp-functions/functions/vshnmariadb/maintenance.go
  pkg/comp-functions/functions/vshnminio/maintenance.go
  pkg/comp-functions/functions/vshnpostgres/maintenance.go
  pkg/comp-functions/functions/vshnredis/maintenance.go
  pkg/maintenance/forgejo.go
  pkg/maintenance/helm/helmpatcher.go
  pkg/maintenance/keycloak.go
  pkg/maintenance/mariadb.go
  pkg/maintenance/minio.go
  pkg/maintenance/nextcloud.go
  pkg/maintenance/postgresql.go
  pkg/maintenance/redis.go
  pkg/maintenance/redis_test.go
  pkg/maintenance/release/release.go
  pkg/maintenance/release/release_test.go
  pkg/scheme.go
  test/functions/vshn-postgres/deploy/01_default.yaml
  test/functions/vshn-postgres/maintenance/01-GivenSchedule.yaml
  test/functions/vshn-postgres/maintenance/02-GivenNoSchedule.yaml
Labels: patch

#336 Forgejo: Fix backup
  pkg/comp-functions/functions/vshnforgejo/script/backup.sh
Labels: bug, patch
